github.com:
    users:
        IDR0FFI:
            oauth_token: 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
    git_protocol: https
    user: IDR0FFI
    oauth_token: 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
