github.com:
    users:
        IDR0FFI:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: IDR0FFI
